# Site configuration
# 1. Files excluded from Jekyll builds
# 2. Installed Gems
# 3. Gem settings
# 4. Jekyll settings
# 5. Collections
# 6. Jekyll collections settings
# 7. Site settings
# 8. Site navigation

# 1. Files excluded from Jekyll builds
exclude:
- README.md
- LICENSE
- Gemfile
- Gemfile.lock

# 2. Installed Gems
gems:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-feed
- jemoji

# 3. Gem settings
paginate: 5 # jekyll-paginate > items per page
paginate_path: posts/page:num # jekyll-paginate > blog page
jekyll-mentions: https://safenetforum.org/users # jekyll-mentions > service used when @replying
twitter:
  username: SAFEcrossroads # jekyll-seo-tag > Owners twitter username
author: SAFEcrossroads # jekyll-seo-tag > default author
social: # jekyll-seo-tag > social overrides
  name: John Ferguson # jekyll-seo-tag > real name
  links:  # jekyll-seo-tag > social aliases (sameAs)
    - https://twitter.com/SAFEcrossroads

# 4. Jekyll settings
sass:
  style: compressed # Style compression
permalink: /:categories/:title/  # Permalink style (/YYYY/MM/DD/page-name/)
excerpt_separator: <!-- more --> # Marks end of excerpt in posts
timezone: US/Central # Timezone for blog posts and alike

# 5. Collections
collections:
  posts:
    title: Posts # Needed for Siteleaf
    output: true
    # description: "My thoughts and ideas" # The post list page content

# 6. Jekyll collections settings
defaults:
  -
    scope:
      path: ""
      type: pages
    values:
      layout: page # Default layout
      image: "/assets/safecrossroads-social.png" # Default image for sharing
  -
    scope:
      path: ""
      type: posts
    values:
      layout: post # Default layout
      image: "/assets/safecrossroads-social.png" # Default image for sharing

# 7. Site settings
encoding: utf-8 # Make sure the encoding is right
title: "SAFE Crossroads" # Site name or title, also used in jekyll-seo-tag
logo: "/assets/safecrossroads-logo.png" # Site logo, also used in jekyll-seo-tag
description: "SAFE Crossroads covers the technology, applications, ideas and people of SAFE Network, where SAFE stands for Secure Access For Everyone, with the keynote of Privacy, Security and Freedom for all." # Site description and default description, also used in jekyll-seo-tag
url: "https://safecrossroads.net" # Site url, also used in jekyll-seo-tag
repo: "https://github.com/safecrossroads/safecrossroads.net"
email: "simpleton@safecrossroads.net"
favicon: "/assets/safecrossroads-apple-touch-icon.png"

# 8. Site navigation
navigation_header:
  Posts: /posts/
  Categories: /categories/
  Subscribe: /subscribe/
  Contribute: /contribute/
  Search: /search/

navigation_footer:
  Subscribe: /subscribe/
  Contribute: /contribute/
  Search: /search/

social_links:
  Twitter: https://twitter.com/safecrossroads
  GitHub: https://github.com/safecrossroads/safecrossroads.net
  Email: mailto:simpleton@safecrossroads.net

sharing_links:
  Twitter: "#1DA1F2"
  Facebook: "#3B5998"
  Email: ""
